name: Docker CI
on: [push]
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile --tag vrc-osc-spotify:$(date +%s)
